[versions]
multimod = "0.2.2"

minecraft = "26.1-snapshot-1"
minecraft-release = "26.1-snapshot-1"

fabric-api = "0.140.2+26.1"

neoforge = "26.1.0.0-alpha.3+snapshot-1"

[libraries]
minecraft = {group = "com.mojang", name = "minecraft", version.ref = "minecraft"}
fabric-api = {group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api"}

[plugins]
multimod = {id = "xyz.eclipseisoffline.multimod", version.ref = "multimod"}
